export const INIT_APP = 'INIT_APP';

export const TOGGLE_SIGN_IN_UP_MODAL = 'TOGGLE_SIGN_IN_UP_MODAL';

export const GET_HOTEL_INFO_BY_ID = 'GET_HOTEL_INFO_BY_ID';
export const GET_HOTEL_INFO_BY_ID_SUCCESS = 'GET_HOTEL_INFO_BY_ID_SUCCESS';
