export const INIT_APP = 'INIT_APP';

export const TOGGLE_SIGN_IN_UP_MODAL = 'TOGGLE_SIGN_IN_UP_MODAL';
export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED';
export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED';
export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const CLEAR_AUTH_ERRORS = 'CLEAR_AUTH_ERRORS';

export const GET_USER_INFO = 'GET_USER_INFO';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const UPDATE_USER_INFO_SUCCESS = 'UPDATE_USER_INFO_SUCCESS';
export const GET_USER_FAVOURITES = 'GET_USER_FAVOURITES';
export const GET_USER_FAVOURITES_SUCCESS = 'GET_USER_FAVOURITES_SUCCESS';
export const ADD_FAVOURITES = 'ADD_FAVOURITES';
export const ADD_FAVOURITES_SUCCESS = 'ADD_FAVOURITES_SUCCESS';
export const CHECK_FOR_OLD_PASSWORD = 'CHECK_FOR_OLD_PASSWORD';
export const CHECK_FOR_OLD_PASSWORD_SUCCESS = 'CHECK_FOR_OLD_PASSWORD_SUCCESS';
export const CHECK_FOR_OLD_PASSWORD_FAILED = 'CHECK_FOR_OLD_PASSWORD_FAILED';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILED = 'CHANGE_PASSWORD_FAILED';
export const CLEAR_SETTINGS = 'CLEAR_SETTINGS';

export const SET_SEARCH_FIELDS = 'SET_SEARCH_FIELDS';
export const GET_HOTELS = 'GET_HOTELS';
export const GET_HOTELS_SUCCESS = 'GET_HOTELS_SUCCESS';
export const GET_HOTEL_INFO_BY_ID = 'GET_HOTEL_INFO_BY_ID';
export const GET_HOTEL_INFO_BY_ID_SUCCESS = 'GET_HOTEL_INFO_BY_ID_SUCCESS';
export const CLEAR_CURRENT_HOTEL = 'CLEAR_CURRENT_HOTEL';
